Repository GoogleCloudPlatform/gke-rbac-demo, pull requests merged in 2019-02, with the labels that each got.

#23 Set resources for Jenkins pod
  Jenkinsfile
Labels: cla: yes, gke-helmsman, lgtm, size/XS

#21 update: boilerplate files in test folder
  Makefile
  test/boilerplate/boilerplate.BUILD.txt
  test/boilerplate/boilerplate.WORKSPACE.txt
  test/boilerplate/boilerplate.bazel.txt
  test/boilerplate/boilerplate.bzl.txt
  test/boilerplate/boilerplate.css.txt
  test/boilerplate/boilerplate.go.preamble
  test/boilerplate/boilerplate.html.preamble
  test/boilerplate/boilerplate.html.txt
  test/boilerplate/boilerplate.java.txt
  test/boilerplate/boilerplate.js.txt
  test/boilerplate/boilerplate.py.preamble
  test/boilerplate/boilerplate.scss.txt
  test/boilerplate/boilerplate.sh.preamble
  test/boilerplate/boilerplate.ts.txt
  test/boilerplate/boilerplate.xml.preamble
  test/verify_boilerplate.py
Labels: approved, cla: yes, gke-helmsman, size/L

#24 Increase node pool size to 2 to support the demo workflow
  terraform/variables.tf
Labels: cla: yes, gke-helmsman, lgtm, size/XS

#25 Updated READme, fixed terraform code for private cluster
  README.md
  img/cluster_in_console_updated.png
  terraform/main.tf
  terraform/variables.tf
Labels: approved, cla: yes, gke-helmsman, lgtm, size/M
